#Programer: Gabriel Hart
#Last Edit: 3/5/22
print("Welcom to The Last Kids on Earth Madlibs")
Adj1 = input("Give me an Adjective: ")
Adj2 = input("Give me an another Adjective: ")
Silly1 = input("Give me a silly word: ")
Occ1 = input("Give me an Occupation: ")
Plur1 = input("Give me a plural noun: ")
Liq1 = input("Give me a type of liquid: ")
Noun1 = input("Give me a Noun: ")
Adj3 = input("Give me an Adjective: ")
Celeb1 = input("Name a Celebrity: ")
Exclam1 = input("Give me an Exclamation: ")
Adj4 = input("Give me an Adjective: ")
Num1 = input("Give me a Number: ")
Num2 = input("Give me another number: ")
Anim1 = input("Name an Animal: ")
Per1 = input("Name a person in the room: ")
Num3 = input("Give me a Number: ")
Verb1 = input("Give me a verb ending in ING: ")
Noun2 = input("Give me a Noun: ")
print("")
print("Title: Meet The Families")
print("My name is Jack Sullivan.  I've been a foster kid my whole life and I've")
print("lived with a lot of", Adj1, "famiies.  Here are some of the most")
print(Adj2, "ones:")
print("")
print("1. The", Silly1, "family: The Mom was a super-important")
print(Occ1, ", so she was never home.  The dad liked to sit on")
print("the couch, watch", Plur1, ", and drink", Liq1, ".")
print("They once gave me a/an", Noun1, "for my birthday, though,")
print("so they weren't all", Adj3, ".")
print("")
print("2. The", Celeb1, "family:", Exclam1, "!  This place was")
print(Adj4, "!  They had", Num1, "kids and", Num2, "pets,")
print("all living under one roof.  They even had a/an", Anim1, "!  Too")
print("bad I was allergic to it.")
print("")
print("3.", Per1, ":  We live together for", Num3, "years, and")
print("there were all these rules, like, 'No", Verb1, "in the")
print("house.'  I'm glad the", Noun2, "Apocalypse happened, so I")
print("don't have to live there anymore!")
